// lib/pages/reminders_list_page.dart
// ignore_for_file: use_build_context_synchronously

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_chat_demo/providers/providers.dart';
import 'package:intl/intl.dart';
import 'package:provider/provider.dart';

// ─────────────────────────────────────────────────────────────────────────────
// FILTER ENUM
// ─────────────────────────────────────────────────────────────────────────────

enum _RFilter { all, today, high, ai }

extension _RFilterX on _RFilter {
  String get label {
    switch (this) {
      case _RFilter.all:
        return 'Tất cả';
      case _RFilter.today:
        return '📅 Hôm nay';
      case _RFilter.high:
        return '🔴 Khẩn';
      case _RFilter.ai:
        return '⚡ AI';
    }
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// PAGE
// ─────────────────────────────────────────────────────────────────────────────

class RemindersListPage extends StatefulWidget {
  final String currentUserId;
  final String? conversationId;
  final String? peerName;

  const RemindersListPage({
    super.key,
    required this.currentUserId,
    this.conversationId,
    this.peerName,
  });

  @override
  State<RemindersListPage> createState() => _RemindersListPageState();
}

class _RemindersListPageState extends State<RemindersListPage>
    with TickerProviderStateMixin {
  late final AnimationController _headerAnim;
  late final AnimationController _listAnim;

  _RFilter _filter = _RFilter.all;
  bool _showDone = false;
  bool _isLoading = false;

  // AI suggestions
  List<ReminderSuggestion> _suggestions = [];
  bool _loadingSuggestions = false;

  @override
  void initState() {
    super.initState();
    _headerAnim = AnimationController(
        vsync: this, duration: const Duration(milliseconds: 600))
      ..forward();
    _listAnim = AnimationController(
        vsync: this, duration: const Duration(milliseconds: 400))
      ..forward();

    WidgetsBinding.instance.addPostFrameCallback((_) => _loadSuggestions());
  }

  @override
  void dispose() {
    _headerAnim.dispose();
    _listAnim.dispose();
    super.dispose();
  }

  // ── AI Suggestions ─────────────────────────────────────────────────────────

  Future<void> _loadSuggestions() async {
    if (!mounted) return;
    setState(() => _loadingSuggestions = true);
    try {
      final provider = context.read<ReminderProvider>();
      final existing = await _fetchCurrentReminders(provider);
      final suggestions = await provider.getAISuggestions(
        userId: widget.currentUserId,
        recentMessages: const [], // caller can pass real messages
        existingReminders: existing,
      );
      if (mounted) setState(() => _suggestions = suggestions.take(3).toList());
    } catch (_) {
    } finally {
      if (mounted) setState(() => _loadingSuggestions = false);
    }
  }

  Future<List<EnhancedReminder>> _fetchCurrentReminders(
      ReminderProvider p) async {
    try {
      final snap = await p.firebaseFirestore
          .collection('reminders')
          .where('userId', isEqualTo: widget.currentUserId)
          .where('isCompleted', isEqualTo: false)
          .limit(20)
          .get();
      return snap.docs
          .map((d) => EnhancedReminder.fromMap(d.id, d.data()))
          .toList();
    } catch (_) {
      return [];
    }
  }

  // ── Filters ────────────────────────────────────────────────────────────────

  List<EnhancedReminder> _apply(List<EnhancedReminder> all) {
    switch (_filter) {
      case _RFilter.all:
        return all;
      case _RFilter.today:
        final now = DateTime.now();
        return all.where((r) {
          final d = r.reminderTime;
          return d.year == now.year && d.month == now.month && d.day == now.day;
        }).toList();
      case _RFilter.high:
        return all.where((r) => r.priority == ReminderPriority.high).toList();
      case _RFilter.ai:
        return all.where((r) => r.isAutoGenerated).toList();
    }
  }

  // ── Actions ────────────────────────────────────────────────────────────────

  Future<void> _complete(String id, ThemePalette p) async {
    HapticFeedback.lightImpact();
    final ok = await context.read<ReminderProvider>().completeReminder(id);
    if (!mounted) return;
    _snackbar(ok ? '✅ Đã hoàn thành!' : '❌ Lỗi',
        color: ok ? const Color(0xFF22C55E) : p.dangerColor);
  }

  Future<void> _delete(String id, ThemePalette p) async {
    final ok = await showDialog<bool>(
      context: context,
      builder: (_) => _ConfirmDlg(palette: p),
    );
    if (ok != true || !mounted) return;
    await context.read<ReminderProvider>().deleteReminder(id);
    if (!mounted) return;
    _snackbar('🗑 Đã xóa nhắc nhở');
  }

  void _snoozeSheet(EnhancedReminder r) {
    HapticFeedback.lightImpact();
    final p = context.read<ThemeProvider>().palette;
    final theme = context.read<ThemeProvider>();
    showModalBottomSheet(
      context: context,
      backgroundColor: Colors.transparent,
      isScrollControlled: true,
      builder: (_) => _SnoozeSheet(
        reminder: r,
        palette: p,
        theme: theme,
        onSnooze: (opt) async {
          Navigator.pop(context);
          final ok = await context
              .read<ReminderProvider>()
              .snoozeReminder(r.id, option: opt);
          if (!mounted) return;
          _snackbar(
            ok ? '⏰ Đã hoãn: ${opt.label}' : '❌ Lỗi',
            color: ok ? const Color(0xFF6C63FF) : p.dangerColor,
          );
        },
      ),
    );
  }

  void _editSheet(EnhancedReminder r) {
    final p = context.read<ThemeProvider>().palette;
    final theme = context.read<ThemeProvider>();
    showModalBottomSheet(
      context: context,
      backgroundColor: Colors.transparent,
      isScrollControlled: true,
      useSafeArea: true,
      builder: (_) => _EditSheet(
        reminder: r,
        palette: p,
        theme: theme,
        onSave: (time, priority) async {
          Navigator.pop(context);
          await context.read<ReminderProvider>().updateReminder(
                reminderId: r.id,
                newReminderTime: time,
                priority: priority,
              );
          if (!mounted) return;
          _snackbar('✅ Đã cập nhật nhắc nhở', color: const Color(0xFF22C55E));
        },
      ),
    );
  }

  void _addSheet() {
    final p = context.read<ThemeProvider>().palette;
    final theme = context.read<ThemeProvider>();
    showModalBottomSheet(
      context: context,
      backgroundColor: Colors.transparent,
      isScrollControlled: true,
      useSafeArea: true,
      builder: (_) => _AddSheet(
        palette: p,
        theme: theme,
        userId: widget.currentUserId,
        conversationId: widget.conversationId,
        provider: context.read<ReminderProvider>(),
        onCreated: () {
          if (!mounted) return;
          _snackbar('✅ Đã tạo nhắc nhở!', color: const Color(0xFF22C55E));
          _loadSuggestions();
        },
      ),
    );
  }

  void _snackbar(String msg, {Color? color}) {
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(SnackBar(
      content: Text(msg, style: const TextStyle(fontWeight: FontWeight.w600)),
      behavior: SnackBarBehavior.floating,
      backgroundColor: color,
      duration: const Duration(seconds: 2),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      margin: const EdgeInsets.fromLTRB(16, 0, 16, 16),
    ));
  }

  // ══════════════════════════════════════════════════════════════════════════
  // BUILD
  // ══════════════════════════════════════════════════════════════════════════

  @override
  Widget build(BuildContext context) {
    final theme = context.watch<ThemeProvider>();
    final p = theme.palette;

    return Theme(
      data: theme.isDark ? theme.darkTheme : theme.lightTheme,
      child: Scaffold(
        backgroundColor: p.background,
        body: Stack(children: [
          NestedScrollView(
            headerSliverBuilder: (_, inner) => [
              _AppBar(
                peerName: widget.peerName,
                palette: p,
                theme: theme,
                headerAnim: _headerAnim,
                showDone: _showDone,
                onToggleDone: () => setState(() => _showDone = !_showDone),
                filter: _filter,
                onFilter: (f) {
                  HapticFeedback.selectionClick();
                  setState(() => _filter = f);
                },
              ),
            ],
            body: StreamBuilder<List<EnhancedReminder>>(
              stream: context
                  .read<ReminderProvider>()
                  .getEnhancedRemindersStream(widget.currentUserId),
              builder: (_, snap) {
                if (snap.connectionState == ConnectionState.waiting &&
                    !snap.hasData) {
                  return _Skeleton(palette: p);
                }
                final all = snap.data ?? [];
                final filtered = _apply(all);
                return _Body(
                  all: all,
                  filtered: filtered,
                  showDone: _showDone,
                  suggestions: _suggestions,
                  loadingSugg: _loadingSuggestions,
                  userId: widget.currentUserId,
                  palette: p,
                  theme: theme,
                  provider: context.read<ReminderProvider>(),
                  onComplete: _complete,
                  onDelete: _delete,
                  onSnooze: _snoozeSheet,
                  onEdit: _editSheet,
                  onAddFromSugg: (sug) => _addFromSuggestion(sug, p, theme),
                );
              },
            ),
          ),
          if (_isLoading)
            Container(
              color: Colors.black26,
              child: Center(
                child: CircularProgressIndicator(
                    color: theme.primaryColor, strokeWidth: 2.5),
              ),
            ),
        ]),
        floatingActionButton: _FAB(
          primaryColor: theme.primaryColor,
          onTap: _addSheet,
        ),
      ),
    );
  }

  void _addFromSuggestion(
    ReminderSuggestion sug,
    ThemePalette p,
    ThemeProvider theme,
  ) {
    showModalBottomSheet(
      context: context,
      backgroundColor: Colors.transparent,
      isScrollControlled: true,
      useSafeArea: true,
      builder: (_) => _AddSheet(
        palette: p,
        theme: theme,
        userId: widget.currentUserId,
        conversationId: widget.conversationId,
        provider: context.read<ReminderProvider>(),
        prefillMessage: sug.task,
        prefillPriority: sug.priority,
        onCreated: () {
          if (!mounted) return;
          _snackbar('✅ Đã thêm nhắc nhở AI!', color: const Color(0xFF22C55E));
          setState(() => _suggestions.remove(sug));
        },
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// SLIVER APP BAR
// ─────────────────────────────────────────────────────────────────────────────

class _AppBar extends StatelessWidget {
  final String? peerName;
  final ThemePalette palette;
  final ThemeProvider theme;
  final AnimationController headerAnim;
  final bool showDone;
  final VoidCallback onToggleDone;
  final _RFilter filter;
  final void Function(_RFilter) onFilter;

  const _AppBar({
    required this.peerName,
    required this.palette,
    required this.theme,
    required this.headerAnim,
    required this.showDone,
    required this.onToggleDone,
    required this.filter,
    required this.onFilter,
  });

  @override
  Widget build(BuildContext context) {
    final p = palette;
    return SliverAppBar(
      expandedHeight: 148,
      pinned: true,
      floating: false,
      backgroundColor: p.appBarBackground,
      elevation: 0,
      surfaceTintColor: Colors.transparent,
      leading: IconButton(
        icon: Icon(Icons.arrow_back_ios_new_rounded,
            color: p.textPrimary, size: 20),
        onPressed: () => Navigator.pop(context),
      ),
      actions: [
        IconButton(
          icon: Icon(
            showDone
                ? Icons.visibility_off_rounded
                : Icons.check_circle_outline_rounded,
            color: p.textSecondary,
            size: 22,
          ),
          tooltip: showDone ? 'Ẩn hoàn thành' : 'Xem hoàn thành',
          onPressed: onToggleDone,
        ),
        const SizedBox(width: 4),
      ],
      flexibleSpace: FlexibleSpaceBar(
        titlePadding: const EdgeInsets.fromLTRB(20, 0, 20, 58),
        title: FadeTransition(
          opacity: CurvedAnimation(parent: headerAnim, curve: Curves.easeOut),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Container(
                width: 34,
                height: 34,
                decoration: BoxDecoration(
                  gradient: LinearGradient(colors: [
                    const Color(0xFF6C63FF),
                    theme.primaryColor,
                  ]),
                  borderRadius: BorderRadius.circular(10),
                  boxShadow: [
                    BoxShadow(
                      color: const Color(0xFF6C63FF).withValues(alpha: 0.35),
                      blurRadius: 10,
                      offset: const Offset(0, 4),
                    )
                  ],
                ),
                child: const Icon(Icons.alarm_rounded,
                    color: Colors.white, size: 18),
              ),
              const SizedBox(width: 10),
              Expanded(
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text('Nhắc nhở',
                        style: TextStyle(
                          color: p.textPrimary,
                          fontSize: 18,
                          fontWeight: FontWeight.w800,
                          letterSpacing: -0.4,
                        )),
                    if (peerName != null)
                      Text('Chat với $peerName',
                          style:
                              TextStyle(color: p.textSecondary, fontSize: 11)),
                  ],
                ),
              ),
            ],
          ),
        ),
        background: _HeaderBg(palette: p, primaryColor: theme.primaryColor),
      ),
      bottom: PreferredSize(
        preferredSize: const Size.fromHeight(46),
        child: Container(
          color: p.appBarBackground,
          padding: const EdgeInsets.fromLTRB(14, 0, 14, 10),
          child: SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: Row(
              children: _RFilter.values.map((f) {
                final active = filter == f;
                return GestureDetector(
                  onTap: () => onFilter(f),
                  child: AnimatedContainer(
                    duration: const Duration(milliseconds: 200),
                    margin: const EdgeInsets.only(right: 8),
                    padding:
                        const EdgeInsets.symmetric(horizontal: 14, vertical: 6),
                    decoration: BoxDecoration(
                      color: active ? theme.primaryColor : p.surfaceVariant,
                      borderRadius: BorderRadius.circular(20),
                      boxShadow: active
                          ? [
                              BoxShadow(
                                color:
                                    theme.primaryColor.withValues(alpha: 0.3),
                                blurRadius: 8,
                                offset: const Offset(0, 3),
                              )
                            ]
                          : null,
                    ),
                    child: Text(f.label,
                        style: TextStyle(
                          color: active ? Colors.white : p.textSecondary,
                          fontSize: 12.5,
                          fontWeight:
                              active ? FontWeight.w700 : FontWeight.w500,
                        )),
                  ),
                );
              }).toList(),
            ),
          ),
        ),
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// BODY
// ─────────────────────────────────────────────────────────────────────────────

class _Body extends StatelessWidget {
  final List<EnhancedReminder> all;
  final List<EnhancedReminder> filtered;
  final bool showDone;
  final List<ReminderSuggestion> suggestions;
  final bool loadingSugg;
  final String userId;
  final ThemePalette palette;
  final ThemeProvider theme;
  final ReminderProvider provider;
  final Future<void> Function(String, ThemePalette) onComplete;
  final Future<void> Function(String, ThemePalette) onDelete;
  final void Function(EnhancedReminder) onSnooze;
  final void Function(EnhancedReminder) onEdit;
  final void Function(ReminderSuggestion) onAddFromSugg;

  const _Body({
    required this.all,
    required this.filtered,
    required this.showDone,
    required this.suggestions,
    required this.loadingSugg,
    required this.userId,
    required this.palette,
    required this.theme,
    required this.provider,
    required this.onComplete,
    required this.onDelete,
    required this.onSnooze,
    required this.onEdit,
    required this.onAddFromSugg,
  });

  @override
  Widget build(BuildContext context) {
    final p = palette;
    if (filtered.isEmpty && !showDone && suggestions.isEmpty) {
      return _EmptyState(palette: p, theme: theme);
    }

    return CustomScrollView(
      physics:
          const BouncingScrollPhysics(parent: AlwaysScrollableScrollPhysics()),
      slivers: [
        // ── Stats bar ────────────────────────────────────────────────────
        SliverToBoxAdapter(
          child: _StatsBar(reminders: all, palette: p, theme: theme),
        ),

        // ── AI Suggestions ───────────────────────────────────────────────
        if (loadingSugg)
          SliverToBoxAdapter(
            child: _SuggestionSkeleton(palette: p),
          )
        else if (suggestions.isNotEmpty) ...[
          SliverToBoxAdapter(
            child: _SectionHdr(
              label: '✨ Gợi ý từ AI',
              color: theme.primaryColor,
              palette: p,
            ),
          ),
          SliverToBoxAdapter(
            child: SizedBox(
              height: 86,
              child: ListView.separated(
                scrollDirection: Axis.horizontal,
                padding: const EdgeInsets.fromLTRB(16, 0, 16, 0),
                itemCount: suggestions.length,
                separatorBuilder: (_, __) => const SizedBox(width: 10),
                itemBuilder: (_, i) => _SuggestionChip(
                  suggestion: suggestions[i],
                  primaryColor: theme.primaryColor,
                  palette: p,
                  onTap: () => onAddFromSugg(suggestions[i]),
                ),
              ),
            ),
          ),
          const SliverToBoxAdapter(child: SizedBox(height: 8)),
        ],

        // ── Due Soon ─────────────────────────────────────────────────────
        ..._section(
          items: filtered.where((r) => r.isDueSoon).toList(),
          label: '⚡ Sắp đến hạn',
          color: const Color(0xFFEF4444),
          p: p,
          theme: theme,
          context: context,
        ),

        // ── Overdue ──────────────────────────────────────────────────────
        ..._section(
          items: filtered.where((r) => r.isOverdue && !r.isDueSoon).toList(),
          label: '🚨 Quá hạn',
          color: const Color(0xFFDC2626),
          p: p,
          theme: theme,
          context: context,
        ),

        // ── High priority ─────────────────────────────────────────────────
        ..._section(
          items: filtered
              .where((r) =>
                  r.priority == ReminderPriority.high &&
                  !r.isDueSoon &&
                  !r.isOverdue)
              .toList(),
          label: '🔴 Ưu tiên cao',
          color: ReminderPriority.high.color,
          p: p,
          theme: theme,
          context: context,
        ),

        // ── Medium priority ───────────────────────────────────────────────
        ..._section(
          items: filtered
              .where((r) =>
                  r.priority == ReminderPriority.medium &&
                  !r.isDueSoon &&
                  !r.isOverdue)
              .toList(),
          label: '🟡 Ưu tiên trung bình',
          color: ReminderPriority.medium.color,
          p: p,
          theme: theme,
          context: context,
        ),

        // ── Low priority ──────────────────────────────────────────────────
        ..._section(
          items: filtered
              .where((r) =>
                  r.priority == ReminderPriority.low &&
                  !r.isDueSoon &&
                  !r.isOverdue)
              .toList(),
          label: '🟢 Ưu tiên thấp',
          color: ReminderPriority.low.color,
          p: p,
          theme: theme,
          context: context,
        ),

        // ── Completed ─────────────────────────────────────────────────────
        if (showDone) ...[
          SliverToBoxAdapter(
            child: _SectionHdr(
              label: '✅ Đã hoàn thành',
              color: const Color(0xFF22C55E),
              palette: p,
            ),
          ),
          SliverToBoxAdapter(
            child: StreamBuilder<List<EnhancedReminder>>(
              stream: provider.getCompletedRemindersStream(userId),
              builder: (_, snap) {
                final done = snap.data ?? [];
                if (done.isEmpty) {
                  return Padding(
                    padding: const EdgeInsets.all(20),
                    child: Text('Chưa có nhắc nhở hoàn thành',
                        style: TextStyle(color: p.textHint, fontSize: 13)),
                  );
                }
                return Column(
                  children: done
                      .map((r) => _RCard(
                            reminder: r,
                            palette: p,
                            theme: theme,
                            isCompleted: true,
                            onComplete: () {},
                            onSnooze: () {},
                            onDelete: () => onDelete(r.id, p),
                            onEdit: () {},
                          ))
                      .toList(),
                );
              },
            ),
          ),
        ],

        const SliverToBoxAdapter(child: SizedBox(height: 110)),
      ],
    );
  }

  List<Widget> _section({
    required List<EnhancedReminder> items,
    required String label,
    required Color color,
    required ThemePalette p,
    required ThemeProvider theme,
    required BuildContext context,
  }) {
    if (items.isEmpty) return [];
    return [
      SliverToBoxAdapter(
        child: _SectionHdr(
            label: label, color: color, count: items.length, palette: p),
      ),
      SliverList(
        delegate: SliverChildBuilderDelegate(
          (_, i) => _RCard(
            reminder: items[i],
            palette: p,
            theme: theme,
            onComplete: () => onComplete(items[i].id, p),
            onSnooze: () => onSnooze(items[i]),
            onDelete: () => onDelete(items[i].id, p),
            onEdit: () => onEdit(items[i]),
          ),
          childCount: items.length,
        ),
      ),
    ];
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// REMINDER CARD (Swipeable)
// ─────────────────────────────────────────────────────────────────────────────

class _RCard extends StatefulWidget {
  final EnhancedReminder reminder;
  final ThemePalette palette;
  final ThemeProvider theme;
  final bool isCompleted;
  final VoidCallback onComplete;
  final VoidCallback onSnooze;
  final VoidCallback onDelete;
  final VoidCallback onEdit;

  const _RCard({
    required this.reminder,
    required this.palette,
    required this.theme,
    required this.onComplete,
    required this.onSnooze,
    required this.onDelete,
    required this.onEdit,
    this.isCompleted = false,
  });

  @override
  State<_RCard> createState() => _RCardState();
}

class _RCardState extends State<_RCard> with SingleTickerProviderStateMixin {
  late final AnimationController _anim;
  bool _gone = false;

  @override
  void initState() {
    super.initState();
    _anim = AnimationController(
        vsync: this, duration: const Duration(milliseconds: 380))
      ..forward();
  }

  @override
  void dispose() {
    _anim.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (_gone) return const SizedBox.shrink();
    final r = widget.reminder;
    final p = widget.palette;
    final t = widget.theme;

    return FadeTransition(
      opacity: CurvedAnimation(parent: _anim, curve: Curves.easeOut),
      child: SlideTransition(
        position: Tween<Offset>(begin: const Offset(0.04, 0), end: Offset.zero)
            .animate(
                CurvedAnimation(parent: _anim, curve: Curves.easeOutCubic)),
        child: Dismissible(
          key: ValueKey(r.id),
          background: _SwipeBg(
              color: const Color(0xFF22C55E),
              icon: Icons.check_rounded,
              label: 'Xong',
              align: Alignment.centerLeft),
          secondaryBackground: _SwipeBg(
              color: const Color(0xFFEF4444),
              icon: Icons.delete_rounded,
              label: 'Xóa',
              align: Alignment.centerRight),
          onDismissed: (dir) {
            setState(() => _gone = true);
            if (dir == DismissDirection.startToEnd) {
              widget.onComplete();
            } else {
              widget.onDelete();
            }
          },
          child: _CardInner(
            r: r,
            p: p,
            t: t,
            isCompleted: widget.isCompleted,
            onEdit: widget.onEdit,
            onComplete: widget.onComplete,
            onSnooze: widget.onSnooze,
            onDelete: widget.onDelete,
          ),
        ),
      ),
    );
  }
}

class _CardInner extends StatelessWidget {
  final EnhancedReminder r;
  final ThemePalette p;
  final ThemeProvider t;
  final bool isCompleted;
  final VoidCallback onEdit;
  final VoidCallback onComplete;
  final VoidCallback onSnooze;
  final VoidCallback onDelete;

  const _CardInner({
    required this.r,
    required this.p,
    required this.t,
    required this.isCompleted,
    required this.onEdit,
    required this.onComplete,
    required this.onSnooze,
    required this.onDelete,
  });

  @override
  Widget build(BuildContext context) {
    final accentColor = r.isDueSoon
        ? const Color(0xFFEF4444)
        : r.isOverdue
            ? const Color(0xFFDC2626)
            : r.priority.color;

    return Container(
      margin: const EdgeInsets.fromLTRB(16, 4, 16, 4),
      decoration: BoxDecoration(
        color: isCompleted ? p.surface.withValues(alpha: .55) : p.surface,
        borderRadius: BorderRadius.circular(18),
        border: Border.all(
          color: (r.isDueSoon || r.isOverdue)
              ? accentColor.withValues(alpha: .45)
              : r.priority.color.withValues(alpha: .18),
          width: (r.isDueSoon || r.isOverdue) ? 1.4 : 0.7,
        ),
        boxShadow: isCompleted
            ? null
            : [
                BoxShadow(
                  color: accentColor.withValues(alpha: .07),
                  blurRadius: 10,
                  offset: const Offset(0, 3),
                ),
              ],
      ),
      child: Material(
        color: Colors.transparent,
        child: InkWell(
          onTap: isCompleted ? null : onEdit,
          borderRadius: BorderRadius.circular(18),
          splashColor: t.primaryColor.withValues(alpha: .05),
          child: Padding(
            padding: const EdgeInsets.fromLTRB(14, 14, 10, 14),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // ── Left accent bar + icon ───────────────────────────
                Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    GestureDetector(
                      onTap: isCompleted ? null : onComplete,
                      child: AnimatedContainer(
                        duration: const Duration(milliseconds: 200),
                        width: 34,
                        height: 34,
                        decoration: BoxDecoration(
                          color: isCompleted
                              ? const Color(0xFF22C55E).withValues(alpha: .12)
                              : accentColor.withValues(alpha: .12),
                          shape: BoxShape.circle,
                          border: Border.all(
                            color: isCompleted
                                ? const Color(0xFF22C55E).withValues(alpha: .4)
                                : accentColor.withValues(alpha: .35),
                            width: 1.4,
                          ),
                        ),
                        child: Center(
                          child: Icon(
                            isCompleted
                                ? Icons.check_rounded
                                : r.isDueSoon
                                    ? Icons.alarm_on_rounded
                                    : Icons.alarm_rounded,
                            color: isCompleted
                                ? const Color(0xFF22C55E)
                                : accentColor,
                            size: 16,
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
                const SizedBox(width: 12),

                // ── Content ─────────────────────────────────────────
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      // Badges row
                      Wrap(
                        spacing: 6,
                        runSpacing: 4,
                        children: [
                          _Badge(
                            text: '${r.priority.emoji} ${r.priority.label}',
                            color: r.priority.color,
                          ),
                          _Badge(
                            text: '${r.category.emoji} ${r.category.label}',
                            color: t.primaryColor,
                          ),
                          if (r.isAutoGenerated)
                            _Badge(
                              text: '⚡ AI',
                              color: const Color(0xFF6C63FF),
                              gradient: const LinearGradient(colors: [
                                Color(0xFF6C63FF),
                                Color(0xFF2196F3),
                              ]),
                            ),
                          if (r.isDueSoon && !isCompleted)
                            _Badge(
                              text: '🔥 Sắp đến',
                              color: const Color(0xFFEF4444),
                            ),
                          if (r.isOverdue && !isCompleted)
                            _Badge(
                              text: '🚨 Quá hạn',
                              color: const Color(0xFFDC2626),
                            ),
                        ],
                      ),
                      const SizedBox(height: 7),

                      // Message
                      Text(
                        r.message,
                        style: TextStyle(
                          color: isCompleted ? p.textHint : p.textPrimary,
                          fontSize: 14.5,
                          fontWeight: FontWeight.w600,
                          height: 1.4,
                          decoration:
                              isCompleted ? TextDecoration.lineThrough : null,
                          decorationColor: p.textHint,
                        ),
                        maxLines: 2,
                        overflow: TextOverflow.ellipsis,
                      ),
                      const SizedBox(height: 6),

                      // Time + repeat + snooze
                      Row(children: [
                        Icon(Icons.schedule_rounded,
                            size: 13,
                            color: r.isDueSoon || r.isOverdue
                                ? accentColor
                                : p.textHint),
                        const SizedBox(width: 4),
                        Text(
                          _fmtTime(r.reminderTime),
                          style: TextStyle(
                            color: r.isDueSoon || r.isOverdue
                                ? accentColor
                                : p.textHint,
                            fontSize: 12,
                            fontWeight: r.isDueSoon || r.isOverdue
                                ? FontWeight.w700
                                : FontWeight.w400,
                          ),
                        ),
                        if (r.repeat != ReminderRepeat.none) ...[
                          const SizedBox(width: 8),
                          Icon(Icons.repeat_rounded,
                              size: 11, color: p.textHint),
                          const SizedBox(width: 3),
                          Text(r.repeat.shortLabel,
                              style:
                                  TextStyle(color: p.textHint, fontSize: 11)),
                        ],
                        if (r.snoozeCount > 0) ...[
                          const SizedBox(width: 8),
                          Container(
                            padding: const EdgeInsets.symmetric(
                                horizontal: 6, vertical: 1),
                            decoration: BoxDecoration(
                              color:
                                  const Color(0xFF6C63FF).withValues(alpha: .1),
                              borderRadius: BorderRadius.circular(7),
                            ),
                            child: Text(
                              '${r.snoozeCount}× hoãn',
                              style: const TextStyle(
                                  color: Color(0xFF6C63FF),
                                  fontSize: 10.5,
                                  fontWeight: FontWeight.w600),
                            ),
                          ),
                        ],
                      ]),

                      if (r.deadline != null) ...[
                        const SizedBox(height: 4),
                        Row(children: [
                          Icon(Icons.flag_rounded,
                              size: 12, color: p.warningColor),
                          const SizedBox(width: 4),
                          Text(
                            'Deadline: ${r.deadline}',
                            style: TextStyle(
                                color: p.warningColor,
                                fontSize: 11.5,
                                fontWeight: FontWeight.w500),
                          ),
                        ]),
                      ],

                      // Action bar
                      if (!isCompleted) ...[
                        const SizedBox(height: 10),
                        Row(children: [
                          _ActionBtn(
                            icon: Icons.snooze_rounded,
                            label: 'Hoãn',
                            color: const Color(0xFF6C63FF),
                            onTap: onSnooze,
                          ),
                          const SizedBox(width: 8),
                          _ActionBtn(
                            icon: Icons.check_circle_rounded,
                            label: 'Xong',
                            color: const Color(0xFF22C55E),
                            onTap: onComplete,
                          ),
                        ]),
                      ],
                    ],
                  ),
                ),

                // ── Delete button ────────────────────────────────────
                GestureDetector(
                  onTap: onDelete,
                  child: Padding(
                    padding: const EdgeInsets.all(4),
                    child: Icon(Icons.delete_outline_rounded,
                        size: 18, color: p.textHint),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  String _fmtTime(DateTime dt) {
    final now = DateTime.now();
    final diff = dt.difference(now);

    if (diff.isNegative) {
      final ago = now.difference(dt);
      if (ago.inMinutes < 60) return 'Quá hạn ${ago.inMinutes} phút';
      if (ago.inHours < 24) return 'Quá hạn ${ago.inHours} giờ';
      return 'Quá hạn ${DateFormat('dd/MM HH:mm').format(dt)}';
    }
    if (diff.inMinutes < 60) return 'Còn ${diff.inMinutes} phút';
    if (diff.inHours < 24) {
      if (dt.day == now.day) return 'Hôm nay ${DateFormat('HH:mm').format(dt)}';
    }
    if (dt.day == now.day + 1 && dt.month == now.month && dt.year == now.year)
      return 'Ngày mai ${DateFormat('HH:mm').format(dt)}';
    return DateFormat('HH:mm, dd/MM/yyyy').format(dt);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// STATS BAR
// ─────────────────────────────────────────────────────────────────────────────

class _StatsBar extends StatelessWidget {
  final List<EnhancedReminder> reminders;
  final ThemePalette palette;
  final ThemeProvider theme;

  const _StatsBar(
      {required this.reminders, required this.palette, required this.theme});

  @override
  Widget build(BuildContext context) {
    if (reminders.isEmpty) return const SizedBox.shrink();
    final high =
        reminders.where((r) => r.priority == ReminderPriority.high).length;
    final dueSoon = reminders.where((r) => r.isDueSoon).length;
    final overdue = reminders.where((r) => r.isOverdue).length;
    final p = palette;

    return Container(
      margin: const EdgeInsets.fromLTRB(16, 12, 16, 4),
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 13),
      decoration: BoxDecoration(
        gradient: LinearGradient(colors: [
          const Color(0xFF6C63FF).withValues(alpha: .08),
          theme.primaryColor.withValues(alpha: .08),
        ]),
        borderRadius: BorderRadius.circular(18),
        border: Border.all(color: theme.primaryColor.withValues(alpha: .15)),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: [
          _Stat(
              value: '${reminders.length}',
              label: 'Tổng',
              color: theme.primaryColor),
          _Divider(),
          _Stat(
              value: '$high',
              label: 'Khẩn',
              color: ReminderPriority.high.color),
          _Divider(),
          _Stat(
              value: '$dueSoon',
              label: 'Sắp đến',
              color: const Color(0xFFF59E0B)),
          _Divider(),
          _Stat(
              value: '$overdue',
              label: 'Quá hạn',
              color: const Color(0xFFEF4444)),
        ],
      ),
    );
  }
}

class _Stat extends StatelessWidget {
  final String value, label;
  final Color color;
  const _Stat({required this.value, required this.label, required this.color});

  @override
  Widget build(BuildContext context) => Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(value,
              style: TextStyle(
                  color: color, fontSize: 20, fontWeight: FontWeight.w800)),
          Text(label,
              style: TextStyle(
                  color: color.withValues(alpha: .7),
                  fontSize: 10.5,
                  fontWeight: FontWeight.w500)),
        ],
      );
}

class _Divider extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Container(
      width: 1, height: 30, color: Colors.white.withValues(alpha: .15));
}

// ─────────────────────────────────────────────────────────────────────────────
// AI SUGGESTION CHIP
// ─────────────────────────────────────────────────────────────────────────────

class _SuggestionChip extends StatelessWidget {
  final ReminderSuggestion suggestion;
  final Color primaryColor;
  final ThemePalette palette;
  final VoidCallback onTap;

  const _SuggestionChip({
    required this.suggestion,
    required this.primaryColor,
    required this.palette,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    final p = palette;
    return GestureDetector(
      onTap: onTap,
      child: Container(
        width: 220,
        padding: const EdgeInsets.all(12),
        decoration: BoxDecoration(
          color: p.surface,
          borderRadius: BorderRadius.circular(16),
          border: Border.all(color: primaryColor.withValues(alpha: .25)),
          boxShadow: [
            BoxShadow(
                color: p.shadow, blurRadius: 8, offset: const Offset(0, 3)),
          ],
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisSize: MainAxisSize.min,
          children: [
            Row(children: [
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                decoration: BoxDecoration(
                  gradient: LinearGradient(colors: [
                    const Color(0xFF6C63FF),
                    primaryColor,
                  ]),
                  borderRadius: BorderRadius.circular(6),
                ),
                child: const Text('⚡ AI',
                    style: TextStyle(
                        color: Colors.white,
                        fontSize: 10,
                        fontWeight: FontWeight.w800)),
              ),
              const SizedBox(width: 6),
              _Badge(
                text:
                    '${suggestion.priority.emoji} ${suggestion.priority.label}',
                color: suggestion.priority.color,
              ),
              const Spacer(),
              Icon(Icons.add_circle_rounded, color: primaryColor, size: 18),
            ]),
            const SizedBox(height: 7),
            Text(
              suggestion.task,
              maxLines: 2,
              overflow: TextOverflow.ellipsis,
              style: TextStyle(
                  color: p.textPrimary,
                  fontSize: 12.5,
                  fontWeight: FontWeight.w600,
                  height: 1.35),
            ),
          ],
        ),
      ),
    );
  }
}

class _SuggestionSkeleton extends StatelessWidget {
  final ThemePalette palette;
  const _SuggestionSkeleton({required this.palette});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 86,
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 16),
        child: Row(
          children: List.generate(
            2,
            (_) => Container(
              width: 220,
              margin: const EdgeInsets.only(right: 10),
              decoration: BoxDecoration(
                color: palette.surfaceVariant,
                borderRadius: BorderRadius.circular(16),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// SNOOZE BOTTOM SHEET
// ─────────────────────────────────────────────────────────────────────────────

class _SnoozeSheet extends StatelessWidget {
  final EnhancedReminder reminder;
  final ThemePalette palette;
  final ThemeProvider theme;
  final void Function(SnoozeOption) onSnooze;

  const _SnoozeSheet({
    required this.reminder,
    required this.palette,
    required this.theme,
    required this.onSnooze,
  });

  @override
  Widget build(BuildContext context) {
    final p = palette;
    return Container(
      padding: EdgeInsets.fromLTRB(
          20, 20, 20, MediaQuery.of(context).viewInsets.bottom + 32),
      decoration: BoxDecoration(
        color: p.surface,
        borderRadius: const BorderRadius.vertical(top: Radius.circular(28)),
        boxShadow: [
          BoxShadow(
              color: p.shadowStrong,
              blurRadius: 24,
              offset: const Offset(0, -4))
        ],
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Center(
            child: Container(
              width: 40,
              height: 4,
              margin: const EdgeInsets.only(bottom: 20),
              decoration: BoxDecoration(
                  color: p.divider, borderRadius: BorderRadius.circular(999)),
            ),
          ),
          Row(children: [
            Container(
              width: 44,
              height: 44,
              decoration: BoxDecoration(
                color: const Color(0xFF6C63FF).withValues(alpha: .1),
                borderRadius: BorderRadius.circular(12),
              ),
              child: const Icon(Icons.snooze_rounded,
                  color: Color(0xFF6C63FF), size: 22),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text('Hoãn nhắc nhở',
                      style: TextStyle(
                          color: p.textPrimary,
                          fontSize: 17,
                          fontWeight: FontWeight.w700)),
                  Text(
                    reminder.message.length > 45
                        ? '${reminder.message.substring(0, 45)}…'
                        : reminder.message,
                    style: TextStyle(color: p.textSecondary, fontSize: 12.5),
                  ),
                ],
              ),
            ),
          ]),
          const SizedBox(height: 20),
          ...SnoozeOption.values.map((opt) {
            final newTime = DateTime.now().add(opt.duration);
            return GestureDetector(
              onTap: () => onSnooze(opt),
              child: Container(
                padding:
                    const EdgeInsets.symmetric(horizontal: 14, vertical: 13),
                margin: const EdgeInsets.only(bottom: 8),
                decoration: BoxDecoration(
                  color: p.surfaceVariant,
                  borderRadius: BorderRadius.circular(14),
                  border: Border.all(color: p.divider, width: .6),
                ),
                child: Row(children: [
                  Text(opt.icon, style: const TextStyle(fontSize: 20)),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(opt.label,
                            style: TextStyle(
                                color: p.textPrimary,
                                fontSize: 15,
                                fontWeight: FontWeight.w600)),
                        Text(
                          DateFormat('HH:mm, dd/MM').format(newTime),
                          style: TextStyle(color: p.textHint, fontSize: 12.5),
                        ),
                      ],
                    ),
                  ),
                  Icon(Icons.chevron_right_rounded,
                      color: p.textHint, size: 20),
                ]),
              ),
            );
          }),
        ],
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// EDIT SHEET
// ─────────────────────────────────────────────────────────────────────────────

class _EditSheet extends StatefulWidget {
  final EnhancedReminder reminder;
  final ThemePalette palette;
  final ThemeProvider theme;
  final void Function(DateTime, ReminderPriority) onSave;

  const _EditSheet({
    required this.reminder,
    required this.palette,
    required this.theme,
    required this.onSave,
  });

  @override
  State<_EditSheet> createState() => _EditSheetState();
}

class _EditSheetState extends State<_EditSheet> {
  late DateTime _time;
  late ReminderPriority _priority;

  @override
  void initState() {
    super.initState();
    _time = widget.reminder.reminderTime;
    _priority = widget.reminder.priority;
  }

  @override
  Widget build(BuildContext context) {
    final p = widget.palette;
    final t = widget.theme;
    return _SheetWrapper(
      palette: p,
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _SheetHeader(
            icon: Icons.alarm_add_rounded,
            title: 'Chỉnh sửa nhắc nhở',
            color: t.primaryColor,
            palette: p,
          ),
          const SizedBox(height: 16),
          // Message display
          Container(
            width: double.infinity,
            padding: const EdgeInsets.all(14),
            decoration: BoxDecoration(
              color: p.surfaceVariant,
              borderRadius: BorderRadius.circular(14),
            ),
            child: Text(widget.reminder.message,
                style: TextStyle(color: p.textPrimary, fontSize: 14)),
          ),
          const SizedBox(height: 14),
          _DateTimePicker(
            time: _time,
            palette: p,
            theme: t,
            onChanged: (dt) => setState(() => _time = dt),
          ),
          const SizedBox(height: 14),
          _PrioritySelector(
            selected: _priority,
            palette: p,
            onChanged: (pr) => setState(() => _priority = pr),
          ),
          const SizedBox(height: 20),
          _PrimaryButton(
            label: 'Lưu thay đổi',
            primaryColor: t.primaryColor,
            onTap: () => widget.onSave(_time, _priority),
          ),
        ],
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// ADD SHEET
// ─────────────────────────────────────────────────────────────────────────────

class _AddSheet extends StatefulWidget {
  final ThemePalette palette;
  final ThemeProvider theme;
  final String userId;
  final String? conversationId;
  final ReminderProvider provider;
  final String? prefillMessage;
  final ReminderPriority? prefillPriority;
  final VoidCallback onCreated;

  const _AddSheet({
    required this.palette,
    required this.theme,
    required this.userId,
    required this.provider,
    required this.onCreated,
    this.conversationId,
    this.prefillMessage,
    this.prefillPriority,
  });

  @override
  State<_AddSheet> createState() => _AddSheetState();
}

class _AddSheetState extends State<_AddSheet> {
  late final TextEditingController _msgCtrl;
  DateTime _time = DateTime.now().add(const Duration(hours: 1));
  ReminderPriority _priority = ReminderPriority.medium;
  ReminderCategory _category = ReminderCategory.other;
  ReminderRepeat _repeat = ReminderRepeat.none;
  bool _saving = false;

  @override
  void initState() {
    super.initState();
    _msgCtrl = TextEditingController(text: widget.prefillMessage ?? '');
    _priority = widget.prefillPriority ?? ReminderPriority.medium;
  }

  @override
  void dispose() {
    _msgCtrl.dispose();
    super.dispose();
  }

  Future<void> _save() async {
    if (_msgCtrl.text.trim().isEmpty) return;
    if (_time.isBefore(DateTime.now())) {
      ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('⚠️ Thời gian phải ở tương lai!')));
      return;
    }
    setState(() => _saving = true);
    try {
      final r = await widget.provider.scheduleReminder(
        userId: widget.userId,
        messageId: DateTime.now().millisecondsSinceEpoch.toString(),
        conversationId: widget.conversationId ?? '',
        reminderTime: _time,
        message: _msgCtrl.text.trim(),
        priority: _priority,
        category: _category,
        repeat: _repeat,
      );
      if (!mounted) return;
      Navigator.pop(context);
      if (r != null) widget.onCreated();
    } finally {
      if (mounted) setState(() => _saving = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final p = widget.palette;
    final t = widget.theme;
    return _SheetWrapper(
      palette: p,
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _SheetHeader(
            icon: Icons.add_alarm_rounded,
            title: 'Thêm nhắc nhở',
            color: t.primaryColor,
            palette: p,
          ),
          const SizedBox(height: 16),
          // Message input
          TextField(
            controller: _msgCtrl,
            maxLines: 3,
            style: TextStyle(color: p.textPrimary, fontSize: 14.5),
            decoration: InputDecoration(
              hintText: 'Nội dung nhắc nhở...',
              hintStyle: TextStyle(color: p.textHint),
              filled: true,
              fillColor: p.surfaceVariant,
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(14),
                borderSide: BorderSide.none,
              ),
              focusedBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(14),
                borderSide: BorderSide(color: t.primaryColor, width: 1.5),
              ),
            ),
          ),
          const SizedBox(height: 14),
          _DateTimePicker(
            time: _time,
            palette: p,
            theme: t,
            onChanged: (dt) => setState(() => _time = dt),
          ),
          const SizedBox(height: 14),
          _PrioritySelector(
            selected: _priority,
            palette: p,
            onChanged: (pr) => setState(() => _priority = pr),
          ),
          const SizedBox(height: 10),
          _CategorySelector(
            selected: _category,
            palette: p,
            theme: t,
            onChanged: (c) => setState(() => _category = c),
          ),
          const SizedBox(height: 10),
          _RepeatSelector(
            selected: _repeat,
            palette: p,
            theme: t,
            onChanged: (r) => setState(() => _repeat = r),
          ),
          const SizedBox(height: 20),
          _PrimaryButton(
            label: 'Tạo nhắc nhở',
            primaryColor: t.primaryColor,
            loading: _saving,
            onTap: _save,
          ),
        ],
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// SHARED FORM COMPONENTS
// ─────────────────────────────────────────────────────────────────────────────

class _DateTimePicker extends StatelessWidget {
  final DateTime time;
  final ThemePalette palette;
  final ThemeProvider theme;
  final void Function(DateTime) onChanged;

  const _DateTimePicker({
    required this.time,
    required this.palette,
    required this.theme,
    required this.onChanged,
  });

  @override
  Widget build(BuildContext context) {
    final p = palette;
    return Row(children: [
      Expanded(
        child: _PickerTile(
          icon: Icons.calendar_today_rounded,
          label: 'Ngày',
          value: DateFormat('dd/MM/yyyy').format(time),
          palette: p,
          primary: theme.primaryColor,
          onTap: () async {
            final d = await showDatePicker(
              context: context,
              initialDate: time,
              firstDate: DateTime.now(),
              lastDate: DateTime.now().add(const Duration(days: 365)),
            );
            if (d != null) {
              onChanged(
                  DateTime(d.year, d.month, d.day, time.hour, time.minute));
            }
          },
        ),
      ),
      const SizedBox(width: 10),
      Expanded(
        child: _PickerTile(
          icon: Icons.access_time_rounded,
          label: 'Giờ',
          value: DateFormat('HH:mm').format(time),
          palette: p,
          primary: theme.primaryColor,
          onTap: () async {
            final t = await showTimePicker(
              context: context,
              initialTime: TimeOfDay.fromDateTime(time),
            );
            if (t != null) {
              onChanged(
                  DateTime(time.year, time.month, time.day, t.hour, t.minute));
            }
          },
        ),
      ),
    ]);
  }
}

class _PrioritySelector extends StatelessWidget {
  final ReminderPriority selected;
  final ThemePalette palette;
  final void Function(ReminderPriority) onChanged;

  const _PrioritySelector({
    required this.selected,
    required this.palette,
    required this.onChanged,
  });

  @override
  Widget build(BuildContext context) {
    final p = palette;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text('Mức ưu tiên',
            style: TextStyle(
                color: p.textSecondary,
                fontSize: 12.5,
                fontWeight: FontWeight.w600)),
        const SizedBox(height: 8),
        Row(
          children: ReminderPriority.values.map((pr) {
            final sel = selected == pr;
            return Expanded(
              child: GestureDetector(
                onTap: () {
                  HapticFeedback.selectionClick();
                  onChanged(pr);
                },
                child: AnimatedContainer(
                  duration: const Duration(milliseconds: 200),
                  margin: const EdgeInsets.symmetric(horizontal: 3),
                  padding: const EdgeInsets.symmetric(vertical: 10),
                  decoration: BoxDecoration(
                    color: sel
                        ? pr.color.withValues(alpha: .15)
                        : p.surfaceVariant,
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(
                      color: sel ? pr.color : Colors.transparent,
                      width: 1.5,
                    ),
                  ),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Text(pr.emoji, style: const TextStyle(fontSize: 18)),
                      const SizedBox(height: 4),
                      Text(pr.label,
                          style: TextStyle(
                            color: sel ? pr.color : p.textSecondary,
                            fontSize: 11,
                            fontWeight: FontWeight.w600,
                          )),
                    ],
                  ),
                ),
              ),
            );
          }).toList(),
        ),
      ],
    );
  }
}

class _CategorySelector extends StatelessWidget {
  final ReminderCategory selected;
  final ThemePalette palette;
  final ThemeProvider theme;
  final void Function(ReminderCategory) onChanged;

  const _CategorySelector({
    required this.selected,
    required this.palette,
    required this.theme,
    required this.onChanged,
  });

  @override
  Widget build(BuildContext context) {
    final p = palette;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text('Danh mục',
            style: TextStyle(
                color: p.textSecondary,
                fontSize: 12.5,
                fontWeight: FontWeight.w600)),
        const SizedBox(height: 8),
        SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: Row(
            children: ReminderCategory.values.map((cat) {
              final sel = selected == cat;
              return GestureDetector(
                onTap: () {
                  HapticFeedback.selectionClick();
                  onChanged(cat);
                },
                child: AnimatedContainer(
                  duration: const Duration(milliseconds: 200),
                  margin: const EdgeInsets.only(right: 8),
                  padding:
                      const EdgeInsets.symmetric(horizontal: 12, vertical: 7),
                  decoration: BoxDecoration(
                    color: sel ? theme.primaryColor : p.surfaceVariant,
                    borderRadius: BorderRadius.circular(20),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Text(cat.emoji, style: const TextStyle(fontSize: 13)),
                      const SizedBox(width: 5),
                      Text(cat.label,
                          style: TextStyle(
                            color: sel ? Colors.white : p.textSecondary,
                            fontSize: 12.5,
                            fontWeight: FontWeight.w600,
                          )),
                    ],
                  ),
                ),
              );
            }).toList(),
          ),
        ),
      ],
    );
  }
}

class _RepeatSelector extends StatelessWidget {
  final ReminderRepeat selected;
  final ThemePalette palette;
  final ThemeProvider theme;
  final void Function(ReminderRepeat) onChanged;

  const _RepeatSelector({
    required this.selected,
    required this.palette,
    required this.theme,
    required this.onChanged,
  });

  @override
  Widget build(BuildContext context) {
    final p = palette;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text('Lặp lại',
            style: TextStyle(
                color: p.textSecondary,
                fontSize: 12.5,
                fontWeight: FontWeight.w600)),
        const SizedBox(height: 8),
        SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: Row(
            children: ReminderRepeat.values.map((rep) {
              final sel = selected == rep;
              return GestureDetector(
                onTap: () {
                  HapticFeedback.selectionClick();
                  onChanged(rep);
                },
                child: AnimatedContainer(
                  duration: const Duration(milliseconds: 200),
                  margin: const EdgeInsets.only(right: 8),
                  padding:
                      const EdgeInsets.symmetric(horizontal: 14, vertical: 7),
                  decoration: BoxDecoration(
                    color: sel ? theme.primaryColor : p.surfaceVariant,
                    borderRadius: BorderRadius.circular(20),
                  ),
                  child: Text(rep.label,
                      style: TextStyle(
                        color: sel ? Colors.white : p.textSecondary,
                        fontSize: 12.5,
                        fontWeight: FontWeight.w600,
                      )),
                ),
              );
            }).toList(),
          ),
        ),
      ],
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// MICRO COMPONENTS
// ─────────────────────────────────────────────────────────────────────────────

class _Badge extends StatelessWidget {
  final String text;
  final Color color;
  final Gradient? gradient;
  const _Badge({required this.text, required this.color, this.gradient});

  @override
  Widget build(BuildContext context) => Container(
        padding: const EdgeInsets.symmetric(horizontal: 7, vertical: 2),
        decoration: BoxDecoration(
          color: gradient == null ? color.withValues(alpha: .12) : null,
          gradient: gradient,
          borderRadius: BorderRadius.circular(7),
          border: gradient == null
              ? Border.all(color: color.withValues(alpha: .3), width: .6)
              : null,
        ),
        child: Text(text,
            style: TextStyle(
              color: gradient != null ? Colors.white : color,
              fontSize: 10.5,
              fontWeight: FontWeight.w700,
            )),
      );
}

class _SectionHdr extends StatelessWidget {
  final String label;
  final Color color;
  final int? count;
  final ThemePalette palette;
  const _SectionHdr(
      {required this.label,
      required this.color,
      required this.palette,
      this.count});

  @override
  Widget build(BuildContext context) => Padding(
        padding: const EdgeInsets.fromLTRB(20, 16, 20, 6),
        child: Row(children: [
          Container(
              width: 4,
              height: 16,
              decoration: BoxDecoration(
                  color: color, borderRadius: BorderRadius.circular(2))),
          const SizedBox(width: 10),
          Text(label,
              style: TextStyle(
                  color: color,
                  fontSize: 13,
                  fontWeight: FontWeight.w700,
                  letterSpacing: .3)),
          if (count != null) ...[
            const SizedBox(width: 8),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 7, vertical: 2),
              decoration: BoxDecoration(
                  color: color.withValues(alpha: .12),
                  borderRadius: BorderRadius.circular(10)),
              child: Text('$count',
                  style: TextStyle(
                      color: color, fontSize: 11, fontWeight: FontWeight.w700)),
            ),
          ],
        ]),
      );
}

class _ActionBtn extends StatelessWidget {
  final IconData icon;
  final String label;
  final Color color;
  final VoidCallback onTap;
  const _ActionBtn({
    required this.icon,
    required this.label,
    required this.color,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) => GestureDetector(
        onTap: onTap,
        child: Container(
          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 7),
          decoration: BoxDecoration(
            color: color.withValues(alpha: .08),
            borderRadius: BorderRadius.circular(10),
            border: Border.all(color: color.withValues(alpha: .2), width: .8),
          ),
          child: Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(icon, color: color, size: 14),
              const SizedBox(width: 5),
              Text(label,
                  style: TextStyle(
                      color: color,
                      fontSize: 12.5,
                      fontWeight: FontWeight.w600)),
            ],
          ),
        ),
      );
}

class _SwipeBg extends StatelessWidget {
  final Color color;
  final IconData icon;
  final String label;
  final Alignment align;
  const _SwipeBg({
    required this.color,
    required this.icon,
    required this.label,
    required this.align,
  });

  @override
  Widget build(BuildContext context) => Container(
        margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
        decoration: BoxDecoration(
            color: color, borderRadius: BorderRadius.circular(18)),
        child: Align(
          alignment: align,
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 22),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Icon(icon, color: Colors.white, size: 22),
                const SizedBox(height: 4),
                Text(label,
                    style: const TextStyle(
                        color: Colors.white,
                        fontSize: 12,
                        fontWeight: FontWeight.w700)),
              ],
            ),
          ),
        ),
      );
}

class _PickerTile extends StatelessWidget {
  final IconData icon;
  final String label, value;
  final ThemePalette palette;
  final Color primary;
  final VoidCallback onTap;
  const _PickerTile({
    required this.icon,
    required this.label,
    required this.value,
    required this.palette,
    required this.primary,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    final p = palette;
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
        decoration: BoxDecoration(
          color: p.surfaceVariant,
          borderRadius: BorderRadius.circular(12),
          border: Border.all(color: p.divider),
        ),
        child: Row(children: [
          Icon(icon, color: primary, size: 18),
          const SizedBox(width: 8),
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(label, style: TextStyle(fontSize: 10, color: p.textHint)),
              Text(value,
                  style: TextStyle(
                      color: p.textPrimary,
                      fontWeight: FontWeight.w600,
                      fontSize: 14)),
            ],
          ),
          const Spacer(),
          Icon(Icons.chevron_right_rounded, color: p.textHint, size: 18),
        ]),
      ),
    );
  }
}

class _SheetWrapper extends StatelessWidget {
  final ThemePalette palette;
  final Widget child;
  const _SheetWrapper({required this.palette, required this.child});

  @override
  Widget build(BuildContext context) {
    final p = palette;
    return Container(
      padding: EdgeInsets.fromLTRB(
          20, 20, 20, MediaQuery.of(context).viewInsets.bottom + 32),
      decoration: BoxDecoration(
        color: p.surface,
        borderRadius: const BorderRadius.vertical(top: Radius.circular(28)),
        boxShadow: [
          BoxShadow(
              color: p.shadowStrong,
              blurRadius: 24,
              offset: const Offset(0, -4))
        ],
      ),
      child: SingleChildScrollView(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Center(
              child: Container(
                width: 40,
                height: 4,
                margin: const EdgeInsets.only(bottom: 20),
                decoration: BoxDecoration(
                    color: p.divider, borderRadius: BorderRadius.circular(999)),
              ),
            ),
            child,
          ],
        ),
      ),
    );
  }
}

class _SheetHeader extends StatelessWidget {
  final IconData icon;
  final String title;
  final Color color;
  final ThemePalette palette;
  const _SheetHeader({
    required this.icon,
    required this.title,
    required this.color,
    required this.palette,
  });

  @override
  Widget build(BuildContext context) => Row(children: [
        Container(
          width: 42,
          height: 42,
          decoration: BoxDecoration(
            color: color.withValues(alpha: .1),
            borderRadius: BorderRadius.circular(12),
          ),
          child: Icon(icon, color: color, size: 22),
        ),
        const SizedBox(width: 12),
        Text(title,
            style: TextStyle(
                color: palette.textPrimary,
                fontSize: 17,
                fontWeight: FontWeight.w700)),
      ]);
}

class _PrimaryButton extends StatelessWidget {
  final String label;
  final Color primaryColor;
  final bool loading;
  final VoidCallback onTap;
  const _PrimaryButton({
    required this.label,
    required this.primaryColor,
    required this.onTap,
    this.loading = false,
  });

  @override
  Widget build(BuildContext context) => SizedBox(
        width: double.infinity,
        child: FilledButton(
          onPressed: loading ? null : onTap,
          style: FilledButton.styleFrom(
            backgroundColor: primaryColor,
            padding: const EdgeInsets.symmetric(vertical: 15),
            shape:
                RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
          ),
          child: loading
              ? const SizedBox(
                  width: 20,
                  height: 20,
                  child: CircularProgressIndicator(
                      strokeWidth: 2.5, color: Colors.white))
              : Text(label,
                  style: const TextStyle(
                      fontWeight: FontWeight.w700, fontSize: 15.5)),
        ),
      );
}

class _ConfirmDlg extends StatelessWidget {
  final ThemePalette palette;
  const _ConfirmDlg({required this.palette});

  @override
  Widget build(BuildContext context) {
    final p = palette;
    return AlertDialog(
      backgroundColor: p.surface,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
      title: Text('Xóa nhắc nhở',
          style: TextStyle(color: p.textPrimary, fontWeight: FontWeight.w700)),
      content: Text('Bạn có chắc muốn xóa nhắc nhở này?',
          style: TextStyle(color: p.textSecondary)),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context, false),
          child: Text('Huỷ', style: TextStyle(color: p.textSecondary)),
        ),
        FilledButton(
          style: FilledButton.styleFrom(
              backgroundColor: const Color(0xFFEF4444),
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(10))),
          onPressed: () => Navigator.pop(context, true),
          child: const Text('Xóa'),
        ),
      ],
    );
  }
}

class _EmptyState extends StatelessWidget {
  final ThemePalette palette;
  final ThemeProvider theme;
  const _EmptyState({required this.palette, required this.theme});

  @override
  Widget build(BuildContext context) {
    final p = palette;
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(40),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Container(
              width: 90,
              height: 90,
              decoration: BoxDecoration(
                gradient: LinearGradient(colors: [
                  const Color(0xFF6C63FF).withValues(alpha: .12),
                  theme.primaryColor.withValues(alpha: .12),
                ]),
                shape: BoxShape.circle,
              ),
              child: Icon(Icons.alarm_outlined,
                  size: 40, color: theme.primaryColor),
            ),
            const SizedBox(height: 24),
            Text('Chưa có nhắc nhở nào',
                style: TextStyle(
                    color: p.textPrimary,
                    fontSize: 18,
                    fontWeight: FontWeight.w700)),
            const SizedBox(height: 10),
            Text(
              'AI sẽ tự động tạo nhắc nhở từ tin nhắn,\nhoặc bạn có thể tạo thủ công.',
              textAlign: TextAlign.center,
              style:
                  TextStyle(color: p.textSecondary, fontSize: 14, height: 1.55),
            ),
          ],
        ),
      ),
    );
  }
}

class _Skeleton extends StatefulWidget {
  final ThemePalette palette;
  const _Skeleton({required this.palette});

  @override
  State<_Skeleton> createState() => _SkeletonState();
}

class _SkeletonState extends State<_Skeleton>
    with SingleTickerProviderStateMixin {
  late final AnimationController _ctrl;
  late final Animation<double> _anim;

  @override
  void initState() {
    super.initState();
    _ctrl = AnimationController(
        vsync: this, duration: const Duration(milliseconds: 1100))
      ..repeat(reverse: true);
    _anim = CurvedAnimation(parent: _ctrl, curve: Curves.easeInOut);
  }

  @override
  void dispose() {
    _ctrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: _anim,
      builder: (_, __) {
        final c = widget.palette.isDark
            ? Color.lerp(
                const Color(0xFF1A1A1A), const Color(0xFF252525), _anim.value)!
            : Color.lerp(
                const Color(0xFFEEEEEE), const Color(0xFFE4E4E4), _anim.value)!;
        return ListView.builder(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
          itemCount: 5,
          itemBuilder: (_, __) => Container(
            margin: const EdgeInsets.only(bottom: 10),
            height: 90,
            decoration: BoxDecoration(
                color: c, borderRadius: BorderRadius.circular(18)),
          ),
        );
      },
    );
  }
}

class _HeaderBg extends StatelessWidget {
  final ThemePalette palette;
  final Color primaryColor;
  const _HeaderBg({required this.palette, required this.primaryColor});

  @override
  Widget build(BuildContext context) => Container(
        decoration: BoxDecoration(color: palette.appBarBackground),
        child: Stack(children: [
          Positioned(
            right: -40,
            top: -20,
            child: Container(
              width: 180,
              height: 180,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                color: const Color(0xFF6C63FF).withValues(alpha: .07),
              ),
            ),
          ),
          Positioned(
            right: 60,
            top: 30,
            child: Container(
              width: 80,
              height: 80,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                color: primaryColor.withValues(alpha: .05),
              ),
            ),
          ),
        ]),
      );
}

class _FAB extends StatelessWidget {
  final Color primaryColor;
  final VoidCallback onTap;
  const _FAB({required this.primaryColor, required this.onTap});

  @override
  Widget build(BuildContext context) => FloatingActionButton.extended(
        onPressed: onTap,
        backgroundColor: primaryColor,
        foregroundColor: Colors.white,
        elevation: 6,
        icon: const Icon(Icons.add_alarm_rounded),
        label: const Text('Thêm nhắc nhở',
            style: TextStyle(fontWeight: FontWeight.w700)),
      );
}
