import 'dart:async';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:timezone/timezone.dart' as tz;

import '../models/ai_models.dart'; // Sử dụng MessageReminder từ đây

enum ReminderRepeat { none, daily, weekly, monthly }

// Lưu ý: Class MessageReminder đã được di chuyển sang ai_models.dart.
// Việc chuyển đổi JSON/DocumentSnapshot cục bộ sẽ được bổ trợ thêm extension (bên dưới)
// để không làm vỡ các hàm gọi cũ trong ReminderProvider.

extension MessageReminderX on MessageReminder {
  Map<String, dynamic> toJson() => {
        'userId': userId,
        if (conversationId != null) 'conversationId': conversationId,
        if (messageId != null) 'messageId': messageId,
        'reminderTime': reminderTime.millisecondsSinceEpoch.toString(),
        'message': message, // Model dùng chung ánh xạ message -> task
        'isCompleted': isCompleted,
        'isAutoGenerated': isAutoGenerated,
      };

  bool get isExpired => reminderTime.isBefore(DateTime.now()) && !isCompleted;
}

class ReminderProvider {
  final FirebaseFirestore firebaseFirestore;
  final FlutterLocalNotificationsPlugin notificationsPlugin;

  static const String _collection = 'reminders';

  static const String _channelId = 'message_reminders';
  static const String _channelName = 'Message Reminders';
  static const String _urgentChannelId = 'urgent_reminders';
  static const String _urgentChannelName = 'Urgent Reminders';

  ReminderProvider({
    required this.firebaseFirestore,
    required this.notificationsPlugin,
  });

  Future<MessageReminder?> scheduleReminder({
    required String userId,
    required String messageId,
    required String conversationId,
    required DateTime reminderTime,
    required String message,
    String? senderName,
    String? senderAvatar,
    ReminderRepeat repeat = ReminderRepeat.none,
    String? note,
  }) async {
    try {
      if (reminderTime.isBefore(DateTime.now())) {
        debugPrint('⚠️ Reminder time is in the past');
        return null;
      }

      final data = MessageReminder(
        id: '',
        userId: userId,
        messageId: messageId,
        conversationId: conversationId,
        reminderTime: reminderTime,
        message: message,
        isCompleted: false,
        isAutoGenerated: false,
      );

      final docRef =
          await firebaseFirestore.collection(_collection).add(data.toJson());

      final notifId = docRef.id.hashCode.abs() % 2147483647;
      await _scheduleNotification(
        id: notifId,
        title: senderName != null
            ? 'Reminder from $senderName'
            : 'Message Reminder',
        body: message.length > 60 ? '${message.substring(0, 60)}…' : message,
        scheduledDate: reminderTime,
        payload: '$conversationId|${docRef.id}',
        isUrgent: reminderTime.difference(DateTime.now()).inMinutes <= 15,
      );

      debugPrint('✅ Reminder scheduled → ${reminderTime.toIso8601String()}');
      return MessageReminder.fromMap(docRef.id, data.toJson());
    } catch (e) {
      debugPrint('❌ Error scheduling reminder: $e');
      return null;
    }
  }

  Future<bool> updateReminder({
    required String reminderId,
    required DateTime newReminderTime,
    String? newNote,
  }) async {
    try {
      if (newReminderTime.isBefore(DateTime.now())) {
        debugPrint('⚠️ New reminder time is in the past');
        return false;
      }

      final updates = <String, dynamic>{
        'reminderTime': newReminderTime.millisecondsSinceEpoch.toString(),
        if (newNote != null) 'note': newNote,
      };

      await firebaseFirestore
          .collection(_collection)
          .doc(reminderId)
          .update(updates);

      final oldId = reminderId.hashCode.abs() % 2147483647;
      await notificationsPlugin.cancel(oldId);

      final doc =
          await firebaseFirestore.collection(_collection).doc(reminderId).get();
      if (doc.exists) {
        final reminder = MessageReminder.fromMap(doc.id, doc.data()!);

        await _scheduleNotification(
          id: oldId,
          title: 'Message Reminder',
          body: reminder.message.length > 60
              ? '${reminder.message.substring(0, 60)}…'
              : reminder.message,
          scheduledDate: newReminderTime,
          payload: '${reminder.conversationId}|$reminderId',
          isUrgent: newReminderTime.difference(DateTime.now()).inMinutes <= 15,
        );
      }

      debugPrint('✅ Reminder updated → ${newReminderTime.toIso8601String()}');
      return true;
    } catch (e) {
      debugPrint('❌ Error updating reminder: $e');
      return false;
    }
  }

  Future<void> _scheduleNotification({
    required int id,
    required String title,
    required String body,
    required DateTime scheduledDate,
    String? payload,
    bool isUrgent = false,
  }) async {
    try {
      final tz.TZDateTime scheduledTZ =
          tz.TZDateTime.from(scheduledDate, tz.local);

      final channelId = isUrgent ? _urgentChannelId : _channelId;
      final channelName = isUrgent ? _urgentChannelName : _channelName;

      await notificationsPlugin.zonedSchedule(
        id,
        title,
        body,
        scheduledTZ,
        NotificationDetails(
          android: AndroidNotificationDetails(
            channelId,
            channelName,
            channelDescription: 'Scheduled message reminders',
            importance: isUrgent ? Importance.max : Importance.high,
            priority: isUrgent ? Priority.max : Priority.high,
            icon: 'app_icon',
            largeIcon: const DrawableResourceAndroidBitmap('app_icon'),
            playSound: true,
            enableVibration: true,
            styleInformation: BigTextStyleInformation(body),
            color: const Color(0xFF2196F3),
            category: AndroidNotificationCategory.reminder,
          ),
          iOS: const DarwinNotificationDetails(
            presentAlert: true,
            presentBadge: true,
            presentSound: true,
            sound: 'default',
            interruptionLevel: InterruptionLevel.timeSensitive,
          ),
        ),
        androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle,
        payload: payload,
      );

      debugPrint('🔔 Notification scheduled → id:$id at $scheduledTZ');
    } catch (e) {
      debugPrint('❌ Error scheduling notification: $e');
      rethrow;
    }
  }

  Future<bool> completeReminder(String reminderId) async {
    try {
      await firebaseFirestore.collection(_collection).doc(reminderId).update({
        'isCompleted': true,
        'completedAt': DateTime.now().millisecondsSinceEpoch.toString(),
      });

      await notificationsPlugin.cancel(reminderId.hashCode.abs() % 2147483647);

      debugPrint('✅ Reminder completed: $reminderId');
      return true;
    } catch (e) {
      debugPrint('❌ Error completing reminder: $e');
      return false;
    }
  }

  Future<bool> deleteReminder(String reminderId) async {
    try {
      await firebaseFirestore.collection(_collection).doc(reminderId).delete();
      await notificationsPlugin.cancel(reminderId.hashCode.abs() % 2147483647);
      debugPrint('✅ Reminder deleted: $reminderId');
      return true;
    } catch (e) {
      debugPrint('❌ Error deleting reminder: $e');
      return false;
    }
  }

  Future<bool> snoozeReminder(
    String reminderId, {
    Duration snoozeDuration = const Duration(minutes: 10),
  }) async {
    try {
      final newTime = DateTime.now().add(snoozeDuration);
      return await updateReminder(
        reminderId: reminderId,
        newReminderTime: newTime,
      );
    } catch (e) {
      debugPrint('❌ Error snoozing reminder: $e');
      return false;
    }
  }

  Stream<List<MessageReminder>> getUserRemindersStream(String userId) {
    return firebaseFirestore
        .collection(_collection)
        .where('userId', isEqualTo: userId)
        .where('isCompleted', isEqualTo: false)
        .orderBy('reminderTime')
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => MessageReminder.fromMap(doc.id, doc.data()))
            .toList());
  }

  Stream<List<MessageReminder>> getCompletedRemindersStream(
    String userId, {
    int limit = 50,
  }) {
    return firebaseFirestore
        .collection(_collection)
        .where('userId', isEqualTo: userId)
        .where('isCompleted', isEqualTo: true)
        .orderBy('completedAt', descending: true)
        .limit(limit)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => MessageReminder.fromMap(doc.id, doc.data()))
            .toList());
  }

  Future<List<MessageReminder>> getUpcomingReminders(
    String userId, {
    int minutes = 60,
  }) async {
    try {
      final now = DateTime.now();
      final cutoff = now.add(Duration(minutes: minutes));

      final snapshot = await firebaseFirestore
          .collection(_collection)
          .where('userId', isEqualTo: userId)
          .where('isCompleted', isEqualTo: false)
          .get();

      return snapshot.docs
          .map((doc) => MessageReminder.fromMap(doc.id, doc.data()))
          .where((r) =>
              r.reminderTime.isAfter(now) && r.reminderTime.isBefore(cutoff))
          .toList()
        ..sort((a, b) => a.reminderTime.compareTo(b.reminderTime));
    } catch (e) {
      debugPrint('❌ Error getting upcoming reminders: $e');
      return [];
    }
  }

  Stream<int> getActiveReminderCount(String userId) {
    return firebaseFirestore
        .collection(_collection)
        .where('userId', isEqualTo: userId)
        .where('isCompleted', isEqualTo: false)
        .snapshots()
        .map((s) => s.size);
  }

  Future<void> checkExpiredReminders(String userId) async {
    try {
      final now = DateTime.now();
      final snapshot = await firebaseFirestore
          .collection(_collection)
          .where('userId', isEqualTo: userId)
          .where('isCompleted', isEqualTo: false)
          .get();

      for (final doc in snapshot.docs) {
        final reminder = MessageReminder.fromMap(doc.id, doc.data());
        if (reminder.reminderTime.isBefore(now)) {
          // Lặp lại logic ở đây nếu ứng dụng nâng cấp MessageReminder hỗ trợ properties "Repeat" về sau.
          await completeReminder(reminder.id);
        }
      }
      debugPrint('✅ Expired reminders checked for user: $userId');
    } catch (e) {
      debugPrint('❌ Error checking expired reminders: $e');
    }
  }

  Future<void> cleanupOldReminders(
    String userId, {
    Duration olderThan = const Duration(days: 30),
  }) async {
    try {
      final cutoff = DateTime.now().subtract(olderThan);
      final snapshot = await firebaseFirestore
          .collection(_collection)
          .where('userId', isEqualTo: userId)
          .where('isCompleted', isEqualTo: true)
          .get();

      final batch = firebaseFirestore.batch();
      int count = 0;
      for (final doc in snapshot.docs) {
        final data = doc.data();
        final completedAt = data['completedAt'];
        if (completedAt != null) {
          final ms = int.tryParse(completedAt.toString()) ?? 0;
          final dt = DateTime.fromMillisecondsSinceEpoch(ms);
          if (dt.isBefore(cutoff)) {
            batch.delete(doc.reference);
            count++;
          }
        }
      }
      await batch.commit();
      debugPrint('✅ Cleaned up $count old reminders for user: $userId');
    } catch (e) {
      debugPrint('❌ Error cleaning up old reminders: $e');
    }
  }

  Future<void> cancelAllNotifications() async {
    await notificationsPlugin.cancelAll();
    debugPrint('✅ All notifications cancelled');
  }
}
