// lib/providers/reminder_provider.dart
// ignore_for_file: avoid_print

import 'dart:async';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:timezone/timezone.dart' as tz;

import 'package:flutter_chat_demo/models/ai_models.dart';
import 'package:flutter_chat_demo/models/reminder_models.dart';
import 'package:flutter_chat_demo/services/ai_backend_service.dart';

export 'package:flutter_chat_demo/models/reminder_models.dart';

// ══════════════════════════════════════════════════════════════════════════
// EXTENSIONS
// ══════════════════════════════════════════════════════════════════════════

extension MessageReminderX on MessageReminder {
  Map<String, dynamic> toJson() => {
    'userId': userId,
    if (conversationId != null) 'conversationId': conversationId,
    if (messageId != null) 'messageId': messageId,
    'reminderTime': reminderTime.millisecondsSinceEpoch.toString(),
    'message': message, // Model dùng chung ánh xạ message -> task
    'isCompleted': isCompleted,
    'isAutoGenerated': isAutoGenerated,
  };

  bool get isExpired => reminderTime.isBefore(DateTime.now()) && !isCompleted;
}

// ══════════════════════════════════════════════════════════════════════════
// PROVIDER
// ══════════════════════════════════════════════════════════════════════════

class ReminderProvider {
  final FirebaseFirestore firebaseFirestore;
  final FlutterLocalNotificationsPlugin notificationsPlugin;

  static const _col          = 'reminders';
  static const _chanId       = 'message_reminders';
  static const _chanName     = 'Nhắc nhở tin nhắn';
  static const _urgentChanId = 'urgent_reminders';
  static const _urgentChanNm = 'Nhắc nhở khẩn cấp';

  ReminderProvider({
    required this.firebaseFirestore,
    required this.notificationsPlugin,
  });

  // ══════════════════════════════════════════════════════════════════════════
  // CREATE
  // ══════════════════════════════════════════════════════════════════════════

  Future<EnhancedReminder?> scheduleReminder({
    required String   userId,
    required String   messageId,
    required String   conversationId,
    required DateTime reminderTime,
    required String   message,
    String?           senderName,
    ReminderPriority  priority        = ReminderPriority.medium,
    ReminderCategory  category        = ReminderCategory.other,
    String?           deadline,
    ReminderRepeat    repeat          = ReminderRepeat.none,
    bool              isAutoGenerated = false,
  }) async {
    try {
      if (reminderTime.isBefore(DateTime.now())) {
        debugPrint('⚠️ [Reminder] Time is in the past');
        return null;
      }

      final data = EnhancedReminder(
        id:              '',
        userId:          userId,
        messageId:       messageId,
        conversationId:  conversationId,
        reminderTime:    reminderTime,
        message:         message,
        isAutoGenerated: isAutoGenerated,
        priority:        priority,
        category:        category,
        deadline:        deadline,
        repeat:          repeat,
        createdAt:       DateTime.now(),
      );

      final ref = await firebaseFirestore.collection(_col).add(data.toJson());

      await _scheduleNotif(
        id:            _nid(ref.id),
        title:         _title(senderName, priority),
        body:          message.length > 100
            ? '${message.substring(0, 100)}…'
            : message,
        scheduledDate: reminderTime,
        payload:       '$conversationId|${ref.id}',
        isUrgent:      priority == ReminderPriority.high ||
            reminderTime.difference(DateTime.now()).inMinutes <= 15,
        priority:      priority,
        category:      category,
      );

      debugPrint('✅ [Reminder] Scheduled ${ref.id} at $reminderTime');
      return EnhancedReminder.fromMap(ref.id, data.toJson());
    } catch (e) {
      debugPrint('❌ [Reminder] scheduleReminder: $e');
      return null;
    }
  }

  /// Tạo hàng loạt từ kết quả AI extraction
  Future<List<EnhancedReminder>> scheduleFromExtracted({
    required String                userId,
    required String                conversationId,
    required List<ExtractedReminder> extracted,
  }) async {
    final created = <EnhancedReminder>[];
    for (final item in extracted) {
      if (item.task.isEmpty) continue;
      final r = await scheduleReminder(
        userId:          userId,
        messageId:       item.messageId ?? '',
        conversationId:  conversationId,
        reminderTime:    item.parsedReminderTime,
        message:         item.task,
        priority:        item.priority,
        category:        item.category,
        deadline:        item.deadline,
        isAutoGenerated: true,
      );
      if (r != null) created.add(r);
    }
    return created;
  }

  // ══════════════════════════════════════════════════════════════════════════
  // SNOOZE
  // ══════════════════════════════════════════════════════════════════════════

  Future<bool> snoozeReminder(
      String reminderId, {
        SnoozeOption option = SnoozeOption.fifteenMinutes,
      }) async {
    try {
      final doc = await firebaseFirestore.collection(_col).doc(reminderId).get();
      if (!doc.exists) return false;

      final r       = EnhancedReminder.fromMap(doc.id, doc.data()!);
      final newTime = DateTime.now().add(option.duration);

      await firebaseFirestore.collection(_col).doc(reminderId).update({
        'reminderTime':     newTime.millisecondsSinceEpoch.toString(),
        'snoozeCount':      r.snoozeCount + 1,
        'notificationSent': false,
      });

      await notificationsPlugin.cancel(_nid(reminderId));
      await _scheduleNotif(
        id:            _nid(reminderId),
        title:         '${option.icon} Nhắc lại: ${option.label}',
        body:          r.message.length > 100
            ? '${r.message.substring(0, 100)}…'
            : r.message,
        scheduledDate: newTime,
        payload:       '${r.conversationId}|$reminderId',
        isUrgent:      r.priority == ReminderPriority.high,
        priority:      r.priority,
        category:      r.category,
      );

      return true;
    } catch (e) {
      debugPrint('❌ [Reminder] snoozeReminder: $e');
      return false;
    }
  }

  // ══════════════════════════════════════════════════════════════════════════
  // COMPLETE / DELETE / UPDATE
  // ══════════════════════════════════════════════════════════════════════════

  Future<bool> completeReminder(String reminderId) async {
    try {
      await firebaseFirestore.collection(_col).doc(reminderId).update({
        'isCompleted': true,
        'completedAt': DateTime.now().millisecondsSinceEpoch.toString(),
      });
      await notificationsPlugin.cancel(_nid(reminderId));
      debugPrint('✅ [Reminder] Completed: $reminderId');
      return true;
    } catch (e) {
      debugPrint('❌ [Reminder] completeReminder: $e');
      return false;
    }
  }

  Future<bool> deleteReminder(String reminderId) async {
    try {
      await firebaseFirestore.collection(_col).doc(reminderId).delete();
      await notificationsPlugin.cancel(_nid(reminderId));
      debugPrint('✅ [Reminder] Deleted: $reminderId');
      return true;
    } catch (e) {
      debugPrint('❌ [Reminder] deleteReminder: $e');
      return false;
    }
  }

  Future<bool> updateReminder({
    required String   reminderId,
    required DateTime newReminderTime,
    ReminderPriority? priority,
    String?           newMessage,
    ReminderCategory? category,
  }) async {
    try {
      if (newReminderTime.isBefore(DateTime.now())) return false;

      await firebaseFirestore.collection(_col).doc(reminderId).update({
        'reminderTime':     newReminderTime.millisecondsSinceEpoch.toString(),
        if (priority   != null) 'priority': priority.name,
        if (newMessage != null) 'message':  newMessage,
        if (newMessage != null) 'task':     newMessage,
        if (category   != null) 'category': category.name,
        'notificationSent': false,
      });

      await notificationsPlugin.cancel(_nid(reminderId));
      final doc = await firebaseFirestore.collection(_col).doc(reminderId).get();
      if (doc.exists) {
        final r = EnhancedReminder.fromMap(doc.id, doc.data()!);
        await _scheduleNotif(
          id:            _nid(reminderId),
          title:         _title(null, r.priority),
          body:          r.message.length > 100
              ? '${r.message.substring(0, 100)}…'
              : r.message,
          scheduledDate: newReminderTime,
          payload:       '${r.conversationId}|$reminderId',
          isUrgent:      r.priority == ReminderPriority.high ||
              newReminderTime.difference(DateTime.now()).inMinutes <= 15,
          priority:      r.priority,
          category:      r.category,
        );
      }
      return true;
    } catch (e) {
      debugPrint('❌ [Reminder] updateReminder: $e');
      return false;
    }
  }

  Future<bool> updatePriority(String id, ReminderPriority p) async {
    try {
      await firebaseFirestore
          .collection(_col)
          .doc(id)
          .update({'priority': p.name});
      return true;
    } catch (e) {
      return false;
    }
  }

  // ══════════════════════════════════════════════════════════════════════════
  // STREAMS & QUERIES
  // ══════════════════════════════════════════════════════════════════════════

  Stream<List<EnhancedReminder>> getEnhancedRemindersStream(String userId) =>
      firebaseFirestore
          .collection(_col)
          .where('userId',      isEqualTo: userId)
          .where('isCompleted', isEqualTo: false)
          .orderBy('reminderTime')
          .snapshots()
          .map((s) => s.docs
          .map((d) => EnhancedReminder.fromMap(d.id, d.data()))
          .toList());

  Stream<List<EnhancedReminder>> getCompletedRemindersStream(
      String userId, {
        int limit = 30,
      }) =>
      firebaseFirestore
          .collection(_col)
          .where('userId',      isEqualTo: userId)
          .where('isCompleted', isEqualTo: true)
          .orderBy('completedAt', descending: true)
          .limit(limit)
          .snapshots()
          .map((s) => s.docs
          .map((d) => EnhancedReminder.fromMap(d.id, d.data()))
          .toList());

  Stream<List<EnhancedReminder>> getConversationRemindersStream(
      String convId) =>
      firebaseFirestore
          .collection(_col)
          .where('conversationId', isEqualTo: convId)
          .where('isCompleted',    isEqualTo: false)
          .orderBy('reminderTime')
          .snapshots()
          .map((s) => s.docs
          .map((d) => EnhancedReminder.fromMap(d.id, d.data()))
          .toList());

  Stream<int> getActiveReminderCount(String userId) =>
      firebaseFirestore
          .collection(_col)
          .where('userId',      isEqualTo: userId)
          .where('isCompleted', isEqualTo: false)
          .snapshots()
          .map((s) => s.size);

  Future<List<EnhancedReminder>> getUpcomingReminders(
      String userId, {
        int minutes = 60,
      }) async {
    try {
      final now = DateTime.now();
      final cutoff = now.add(Duration(minutes: minutes));

      final snapshot = await firebaseFirestore
          .collection(_col)
          .where('userId', isEqualTo: userId)
          .where('isCompleted', isEqualTo: false)
          .get();

      return snapshot.docs
          .map((doc) => EnhancedReminder.fromMap(doc.id, doc.data()))
          .where((r) =>
      r.reminderTime.isAfter(now) && r.reminderTime.isBefore(cutoff))
          .toList()
        ..sort((a, b) => a.reminderTime.compareTo(b.reminderTime));
    } catch (e) {
      debugPrint('❌ [Reminder] Error getting upcoming reminders: $e');
      return [];
    }
  }

  /// Backward-compat with old MessageReminder-based code
  Stream<List<MessageReminder>> getUserRemindersStream(String userId) =>
      getEnhancedRemindersStream(userId).map((list) => list
          .map((r) => MessageReminder(
        id:              r.id,
        userId:          r.userId,
        conversationId:  r.conversationId,
        messageId:       r.messageId,
        message:         r.message,
        reminderTime:    r.reminderTime,
        isCompleted:     r.isCompleted,
        isAutoGenerated: r.isAutoGenerated,
      ))
          .toList());

  // ══════════════════════════════════════════════════════════════════════════
  // AI INTEGRATION
  // ══════════════════════════════════════════════════════════════════════════

  /// Tự động phân tích tin nhắn và tạo nhắc nhở nếu phát hiện tác vụ.
  Future<List<EnhancedReminder>> autoExtractAndSchedule({
    required String userId,
    required String conversationId,
    required String message,
    String context = '',
  }) async {
    try {
      final result = await AIBackendService().extractReminderWithPriority(
        message:             message,
        conversationContext: context,
      );
      if (!result.hasReminder || result.isEmpty) return [];
      return scheduleFromExtracted(
        userId:         userId,
        conversationId: conversationId,
        extracted:      result.reminders,
      );
    } catch (e) {
      debugPrint('❌ [Reminder] autoExtractAndSchedule: $e');
      return [];
    }
  }

  /// Lấy gợi ý nhắc nhở từ AI dựa trên lịch sử tin nhắn.
  Future<List<ReminderSuggestion>> getAISuggestions({
    required String                userId,
    required List<String>          recentMessages,
    required List<EnhancedReminder>  existingReminders,
  }) async {
    try {
      return AIBackendService().generateReminderSuggestions(
        recentMessages:    recentMessages,
        existingReminders: existingReminders.map((r) => r.message).toList(),
      );
    } catch (e) {
      debugPrint('❌ [Reminder] getAISuggestions: $e');
      return [];
    }
  }

  // ══════════════════════════════════════════════════════════════════════════
  // MAINTENANCE
  // ══════════════════════════════════════════════════════════════════════════

  Future<void> checkAndHandleExpired(String userId) async {
    try {
      final now  = DateTime.now();
      final snap = await firebaseFirestore
          .collection(_col)
          .where('userId',      isEqualTo: userId)
          .where('isCompleted', isEqualTo: false)
          .get();

      for (final doc in snap.docs) {
        final r = EnhancedReminder.fromMap(doc.id, doc.data());
        if (!r.reminderTime.isBefore(now)) continue;

        if (r.repeat != ReminderRepeat.none) {
          final next = _nextRepeat(r.reminderTime, r.repeat);
          await updateReminder(reminderId: r.id, newReminderTime: next);
        } else if (now.difference(r.reminderTime).inHours > 24) {
          await completeReminder(r.id);
        }
      }
      debugPrint('✅ [Reminder] Expired checked for user: $userId');
    } catch (e) {
      debugPrint('❌ [Reminder] checkAndHandleExpired: $e');
    }
  }

  Future<void> cleanupOldCompleted(String userId,
      {int daysOld = 30}) async {
    try {
      final cutoff = DateTime.now()
          .subtract(Duration(days: daysOld))
          .millisecondsSinceEpoch
          .toString();
      final snap = await firebaseFirestore
          .collection(_col)
          .where('userId',      isEqualTo: userId)
          .where('isCompleted', isEqualTo: true)
          .where('completedAt', isLessThan: cutoff)
          .get();

      if (snap.docs.isEmpty) return;
      final batch = firebaseFirestore.batch();
      for (final d in snap.docs) batch.delete(d.reference);
      await batch.commit();
      debugPrint('✅ [Reminder] Cleaned ${snap.docs.length} old reminders');
    } catch (e) {
      debugPrint('❌ [Reminder] cleanupOldCompleted: $e');
    }
  }

  Future<void> cancelAllNotifications() async {
    await notificationsPlugin.cancelAll();
    debugPrint('✅ [Reminder] All notifications cancelled');
  }

  // ══════════════════════════════════════════════════════════════════════════
  // PRIVATE HELPERS
  // ══════════════════════════════════════════════════════════════════════════

  int _nid(String docId) => docId.hashCode.abs() % 2147483647;

  String _title(String? senderName, ReminderPriority p) {
    final badge = p == ReminderPriority.high   ? '🔴 ' :
    p == ReminderPriority.medium ? '🟡 ' : '🟢 ';
    return senderName?.isNotEmpty == true
        ? '${badge}Nhắc từ $senderName'
        : '${badge}Nhắc nhở tin nhắn';
  }

  DateTime _nextRepeat(DateTime from, ReminderRepeat r) {
    switch (r) {
      case ReminderRepeat.daily:   return from.add(const Duration(days: 1));
      case ReminderRepeat.weekly:  return from.add(const Duration(days: 7));
      case ReminderRepeat.monthly:
        return DateTime(from.year, from.month + 1, from.day,
            from.hour, from.minute);
      case ReminderRepeat.none:    return from;
    }
  }

  Future<void> _scheduleNotif({
    required int              id,
    required String           title,
    required String           body,
    required DateTime         scheduledDate,
    String?                   payload,
    bool                      isUrgent = false,
    ReminderPriority          priority = ReminderPriority.medium,
    ReminderCategory          category = ReminderCategory.other,
  }) async {
    try {
      final tzDate = tz.TZDateTime.from(scheduledDate, tz.local);
      await notificationsPlugin.zonedSchedule(
        id,
        title,
        body,
        tzDate,
        NotificationDetails(
          android: AndroidNotificationDetails(
            isUrgent ? _urgentChanId : _chanId,
            isUrgent ? _urgentChanNm : _chanName,
            channelDescription: 'Nhắc nhở thông minh từ AI Chat',
            importance:  isUrgent ? Importance.max  : Importance.high,
            priority:    isUrgent ? Priority.max    : Priority.high,
            icon:        'app_icon',
            largeIcon:   const DrawableResourceAndroidBitmap('app_icon'),
            playSound:   true,
            enableVibration: true,
            styleInformation: BigTextStyleInformation(
              body,
              contentTitle:  title,
              summaryText:   '${category.emoji} ${category.label}',
            ),
            color:    priority.color,
            category: AndroidNotificationCategory.reminder,
            actions: [
              const AndroidNotificationAction(
                  'snooze_15', '⏰ 15 phút',
                  showsUserInterface: false),
              const AndroidNotificationAction(
                  'snooze_60', '⏰ 1 giờ',
                  showsUserInterface: false),
              const AndroidNotificationAction(
                  'complete', '✅ Xong',
                  showsUserInterface: false),
            ],
          ),
          iOS: DarwinNotificationDetails(
            presentAlert: true,
            presentBadge: true,
            presentSound: true,
            sound: isUrgent ? 'alarm.aiff' : 'default',
            interruptionLevel: isUrgent
                ? InterruptionLevel.critical
                : InterruptionLevel.timeSensitive,
            categoryIdentifier: 'reminder_action',
          ),
        ),
        androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle,
        payload: payload,
      );
    } catch (e) {
      debugPrint('❌ [Reminder] _scheduleNotif: $e');
    }
  }
}