buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        // AGP 8.9.1 tương thích tốt với SDK 35 và Java 17
        classpath 'com.android.tools.build:gradle:8.9.1'

        // ĐÃ SỬA: Thay thế phiên bản lỗi 2.3.21 bằng 2.0.21 để đồng bộ với cấu hình app-level
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.0.21'

        classpath 'com.google.gms:google-services:4.4.2'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.2'
    }
}

plugins {
    id "com.android.application" apply false
    id "com.android.library" apply false
    id "org.jetbrains.kotlin.android" apply false
    id "com.google.gms.google-services" apply false
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://storage.googleapis.com/download.flutter.io" }
    }
}

rootProject.buildDir = '../build'

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}