# JVM
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Java
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio1\\jbr

# Suppress compileSdk warning
android.suppressUnsupportedCompileSdk=36

# Kotlin
kotlin.code.style=official

# Gradle optimization
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true

# Android build optimization
android.enableR8.fullMode=false
android.nonTransitiveRClass=false
android.defaults.buildfeatures.buildconfig=true
android.nonFinalResIds=false

# KAPT
kapt.incremental.apt=true
kapt.use.worker.api=true

# Flutter migrator flags
android.builtInKotlin=false
android.newDsl=false